#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# TODO: Is this the write place for exports (esp PATH)?
export PATH="$HOME/bin:$HOME/Dropbox/bin/:$HOME/.local/bin:$PATH"
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Code

if [[ -n $TMUX ]]; then
    export TERM=screen-256color
fi

# Aliases

if ls --color -d . >/dev/null 2>&1; then
    alias ls='ls --color=auto'
elif ls -G -d . >/dev/null 2>&1; then
    alias ls='ls -G'
fi

alias tree='tree -I "*.pyc|__pycache__"'

# Local config

if [[ -f $HOME/.zshrc.local ]]; then
    source $HOME/.zshrc.local
fi
